name: Rohan Chakravarty Portfolio CI/CD

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Checks out code from the repository

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Write the SSH key to a file and set permissions
          echo "${KEY}" > ssh_key
          chmod 600 ssh_key

          # Add the EC2 instance's host key to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H ${HOST} >> ~/.ssh/known_hosts

          # Create the tmp directory using the absolute path
          ssh -i ssh_key ${USER}@${HOST} "mkdir -p /home/${USER}/tmp"


          # Transfer files using scp
          scp -i ssh_key -r . ${USER}@${HOST}:/home/${USER}/tmp/


          # Deploy files to /var/www/html and clean up
          ssh -i ssh_key ${USER}@${HOST} "
            sudo rm -rf /var/www/html/* && \
            sudo cp -r /home/${USER}/tmp/* /var/www/html/ && \
            sudo rm -rf /home/${USER}/tmp
          "


          # Clean up the local SSH key file
          rm ssh_key


        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

